name: build-json

on:
  schedule:
    - cron: "0 * * * *"   # 毎時0分に実行
  workflow_dispatch: {}    # 手動実行も可

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate JSON
        run: python scripts/fetch.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add api
          git commit -m "update api json [skip ci]" || echo "no changes"
          git push
